name: Android CI

on: 
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: cache gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Download Dependencies
      run: bash ./gradlew androidDependencies
    - name: Run Lint
      run: bash ./gradlew ktlintMainSourceSetCheck
    - name: Run Unit Tests
      run: bash ./gradlew test